### ISSUE TITLE
Last modified dates is the same on all pages, the build date

### ISSUE THREAD

**Issue by PipeItToDevNull** [PipeItToDevNull/rTS_Wiki#436]
Gonna be a conflict between starlight and GHA I am rather certain. Need to ask their discord

**Comment by PipeItToDevNull** [comment]
By default, this feature relies on your repository’s Git history and may not be accurate on some deployment platforms performing [shallow clones](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt). A page can override this setting or the Git-based date using the [lastUpdated frontmatter field](https://starlight.astro.build/reference/frontmatter/#lastupdated).

```
name: Full Clone Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This ensures a full clone
    - name: Run your build steps
      run: |
        echo "Add your build steps here"
```
